steps:
  # Step 1: Compile the Go Application
  - name: 'gcr.io/cloud-builders/go'
    id: 'Compile application'
    env: ['GOPATH=/gopath']
    args: ['build', '-o', 'main', 'main.go']

  # Step 2: Build the Docker image for the Go application
  - id: "Build Docker image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/qwiklabs-gcp-02-d87279478000/my-repository/hello-cloudbuild-dev:v2.0",
        "."
      ]

  # Step 3: Push the Docker image to Artifact Registry
  - id: "Push Docker image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/qwiklabs-gcp-02-d87279478000/my-repository/hello-cloudbuild-dev:v2.0"
      ]

  # Step 4: Apply the production deployment YAML file to the production namespace
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy'
    args: ['-n', 'prod', 'apply', '-f', 'prod/deployment.yaml']
    env:
    - 'CLOUDSDK_COMPUTE_REGION=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'
options:
 logging: CLOUD_LOGGING_ONLY